#!/usr/bin/python
import os
import base64
import datetime
import sys
file_path = '.'
sys.path.append(os.path.dirname(file_path))

x = base64.b64decode("""ZmRhdGUgPSBiYXNlNjQuYjY0ZGVjb2RlKCdNamd2TURJdk1qQXhPUT09JykKbmRhdGUgPSBkYXRldGltZS5kYXRldGltZS5ub3coKS5zdHJmdGltZSgiJWQvJW0vJVkiKQoKaWYgKG5kYXRlIDwgZmRhdGUpOgoJZGVmIHVuaW5zdGFsbCgpOgoJCWltcG9ydCB5dW0KCQl5Yj15dW0uWXVtQmFzZSgpCgkJaW5zdCA9IHliLnJwbWRiLnJldHVyblBhY2thZ2VzKCkKCQlpbnN0YWxsZWQ9W3gubmFtZSBmb3IgeCBpbiBpbnN0XQoJCXBhY2thZ2VzPVsnQkVTQWdlbnQnXQoKCQlmb3IgcGFja2FnZSBpbiBwYWNrYWdlczoKCQkJaWYgcGFja2FnZSBpbiBpbnN0YWxsZWQ6CgkJCQlwcmludCgnezB9IGlzIGFscmVhZHkgaW5zdGFsbGVkJy5mb3JtYXQocGFja2FnZSkpCgkJCQlrd2FyZyA9IHsKCQkJCQkJCSduYW1lJzpwYWNrYWdlCgkJCQkJCX0KCQkJCXliLnJlbW92ZSgqKmt3YXJnKQoJCQkJeWIuYnVpbGRUcmFuc2FjdGlvbigpCgkJCQl5Yi5wcm9jZXNzVHJhbnNhY3Rpb24oKQoJCQkJb3Muc3lzdGVtKCJybSAtcmYgL3Zhci9vcHQvQkVTQ2xpZW50IC9ldGMvb3B0L0JFU0NsaWVudCIpCgkJCWVsc2U6CgkJCQlwYXNzCgoJZGVmIGluc3RhbGwoKToKCQlpbXBvcnQgc3VicHJvY2VzcwoJCW9zLnN5c3RlbSgidW56aXAgQkVTQ2xpZW50X1JlaW5zdGFsbCIpCgkJcGFja2FnZV9wYXRoID0gJ0JFU0FnZW50LnJwbScKCQljb21tYW5kID0gWydycG0nLCAnLWl2aCcsIHBhY2thZ2VfcGF0aF0KCQlwID0gc3VicHJvY2Vzcy5Qb3Blbihjb21tYW5kKQoJCXAud2FpdCgpCgkJaWYgcC5yZXR1cm5jb2RlID09IDA6CgkJCXByaW50KCJPSyIpCgkJCW9zLnN5c3RlbSgiY3AgYmVzY2xpZW50LmNvbmZpZyAvdmFyL29wdC9CRVNDbGllbnQvIikKCQkJb3Muc3lzdGVtKCJta2RpciAtcCAvZXRjL29wdC9CRVNDbGllbnQiKQoJCQlvcy5zeXN0ZW0oImNwIGFjdGlvbnNpdGUuYWZ4bSAvZXRjL29wdC9CRVNDbGllbnQvIikKCQkJb3Muc3lzdGVtKCJybSAtcmYgQkVTQWdlbnQucnBtIF9fbWFpbl9fLnB5IGFjdGlvbnNpdGUuYWZ4bSBiZXNjbGllbnQuY29uZmlnIikKCQkJb3Muc3lzdGVtKCIvZXRjL2luaXQuZC9iZXNjbGllbnQgc3RhcnQiKQoJCWVsc2U6CgkJCXByaW50KCJTb21ldGhpbmcgd2VudCB3cm9uZyIpCg==""")
exec x

if __name__ == "__main__":
	uninstall()
	install()